// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/event_store.proto

package proto;

public final class EventStoreProto {
  private EventStoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dcore_database_models_proto_EventStore_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dcore_database_models_proto_EventStore_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/resources/event_store.proto\022\033" +
      "dcore_database.models.proto\032\037google/prot" +
      "obuf/timestamp.proto\"\331\001\n\nEventStore\022\026\n\016e" +
      "vent_store_id\030\001 \001(\t\022\022\n\nevent_name\030\002 \001(\t\022" +
      "\023\n\013item_number\030\003 \001(\t\022\021\n\titem_type\030\004 \001(\t\022" +
      "\017\n\007user_id\030\005 \001(\005\022\022\n\nuser_login\030\006 \001(\t\022\017\n\007" +
      "node_id\030\007 \001(\005\022\021\n\tnode_code\030\010 \001(\t\022.\n\ncrea" +
      "ted_at\030\t \001(\0132\032.google.protobuf.Timestamp" +
      "B\032\n\005protoB\017EventStoreProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_dcore_database_models_proto_EventStore_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dcore_database_models_proto_EventStore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dcore_database_models_proto_EventStore_descriptor,
        new java.lang.String[] { "EventStoreId", "EventName", "ItemNumber", "ItemType", "UserId", "UserLogin", "NodeId", "NodeCode", "CreatedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
