// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/event_store.proto

package proto;

/**
 * Protobuf type {@code dcore_database.models.proto.EventStore}
 */
public final class EventStore extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dcore_database.models.proto.EventStore)
    EventStoreOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EventStore.newBuilder() to construct.
  private EventStore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventStore() {
    eventStoreId_ = "";
    eventName_ = "";
    itemNumber_ = "";
    itemType_ = "";
    userLogin_ = "";
    nodeCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EventStore();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EventStore(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            eventStoreId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            eventName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            itemNumber_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            itemType_ = s;
            break;
          }
          case 40: {

            userId_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            userLogin_ = s;
            break;
          }
          case 56: {

            nodeId_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeCode_ = s;
            break;
          }
          case 74: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdAt_ != null) {
              subBuilder = createdAt_.toBuilder();
            }
            createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdAt_);
              createdAt_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.EventStoreProto.internal_static_dcore_database_models_proto_EventStore_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.EventStoreProto.internal_static_dcore_database_models_proto_EventStore_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.EventStore.class, proto.EventStore.Builder.class);
  }

  public static final int EVENT_STORE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object eventStoreId_;
  /**
   * <code>string event_store_id = 1;</code>
   * @return The eventStoreId.
   */
  @java.lang.Override
  public java.lang.String getEventStoreId() {
    java.lang.Object ref = eventStoreId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventStoreId_ = s;
      return s;
    }
  }
  /**
   * <code>string event_store_id = 1;</code>
   * @return The bytes for eventStoreId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventStoreIdBytes() {
    java.lang.Object ref = eventStoreId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventStoreId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object eventName_;
  /**
   * <code>string event_name = 2;</code>
   * @return The eventName.
   */
  @java.lang.Override
  public java.lang.String getEventName() {
    java.lang.Object ref = eventName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventName_ = s;
      return s;
    }
  }
  /**
   * <code>string event_name = 2;</code>
   * @return The bytes for eventName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventNameBytes() {
    java.lang.Object ref = eventName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEM_NUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object itemNumber_;
  /**
   * <code>string item_number = 3;</code>
   * @return The itemNumber.
   */
  @java.lang.Override
  public java.lang.String getItemNumber() {
    java.lang.Object ref = itemNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      itemNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string item_number = 3;</code>
   * @return The bytes for itemNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemNumberBytes() {
    java.lang.Object ref = itemNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEM_TYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object itemType_;
  /**
   * <code>string item_type = 4;</code>
   * @return The itemType.
   */
  @java.lang.Override
  public java.lang.String getItemType() {
    java.lang.Object ref = itemType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      itemType_ = s;
      return s;
    }
  }
  /**
   * <code>string item_type = 4;</code>
   * @return The bytes for itemType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemTypeBytes() {
    java.lang.Object ref = itemType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 5;
  private int userId_;
  /**
   * <code>int32 user_id = 5;</code>
   * @return The userId.
   */
  @java.lang.Override
  public int getUserId() {
    return userId_;
  }

  public static final int USER_LOGIN_FIELD_NUMBER = 6;
  private volatile java.lang.Object userLogin_;
  /**
   * <code>string user_login = 6;</code>
   * @return The userLogin.
   */
  @java.lang.Override
  public java.lang.String getUserLogin() {
    java.lang.Object ref = userLogin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userLogin_ = s;
      return s;
    }
  }
  /**
   * <code>string user_login = 6;</code>
   * @return The bytes for userLogin.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserLoginBytes() {
    java.lang.Object ref = userLogin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userLogin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODE_ID_FIELD_NUMBER = 7;
  private int nodeId_;
  /**
   * <code>int32 node_id = 7;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public int getNodeId() {
    return nodeId_;
  }

  public static final int NODE_CODE_FIELD_NUMBER = 8;
  private volatile java.lang.Object nodeCode_;
  /**
   * <code>string node_code = 8;</code>
   * @return The nodeCode.
   */
  @java.lang.Override
  public java.lang.String getNodeCode() {
    java.lang.Object ref = nodeCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeCode_ = s;
      return s;
    }
  }
  /**
   * <code>string node_code = 8;</code>
   * @return The bytes for nodeCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeCodeBytes() {
    java.lang.Object ref = nodeCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 9;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 9;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 9;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return getCreatedAt();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEventStoreIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventStoreId_);
    }
    if (!getEventNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventName_);
    }
    if (!getItemNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, itemNumber_);
    }
    if (!getItemTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, itemType_);
    }
    if (userId_ != 0) {
      output.writeInt32(5, userId_);
    }
    if (!getUserLoginBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userLogin_);
    }
    if (nodeId_ != 0) {
      output.writeInt32(7, nodeId_);
    }
    if (!getNodeCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, nodeCode_);
    }
    if (createdAt_ != null) {
      output.writeMessage(9, getCreatedAt());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEventStoreIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventStoreId_);
    }
    if (!getEventNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventName_);
    }
    if (!getItemNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, itemNumber_);
    }
    if (!getItemTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, itemType_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, userId_);
    }
    if (!getUserLoginBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userLogin_);
    }
    if (nodeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, nodeId_);
    }
    if (!getNodeCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, nodeCode_);
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getCreatedAt());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.EventStore)) {
      return super.equals(obj);
    }
    proto.EventStore other = (proto.EventStore) obj;

    if (!getEventStoreId()
        .equals(other.getEventStoreId())) return false;
    if (!getEventName()
        .equals(other.getEventName())) return false;
    if (!getItemNumber()
        .equals(other.getItemNumber())) return false;
    if (!getItemType()
        .equals(other.getItemType())) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!getUserLogin()
        .equals(other.getUserLogin())) return false;
    if (getNodeId()
        != other.getNodeId()) return false;
    if (!getNodeCode()
        .equals(other.getNodeCode())) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_STORE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventStoreId().hashCode();
    hash = (37 * hash) + EVENT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEventName().hashCode();
    hash = (37 * hash) + ITEM_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getItemNumber().hashCode();
    hash = (37 * hash) + ITEM_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getItemType().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (37 * hash) + USER_LOGIN_FIELD_NUMBER;
    hash = (53 * hash) + getUserLogin().hashCode();
    hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId();
    hash = (37 * hash) + NODE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getNodeCode().hashCode();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.EventStore parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.EventStore parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.EventStore parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.EventStore parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.EventStore parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.EventStore parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.EventStore parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.EventStore parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.EventStore parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.EventStore parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.EventStore parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.EventStore parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.EventStore prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dcore_database.models.proto.EventStore}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dcore_database.models.proto.EventStore)
      proto.EventStoreOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.EventStoreProto.internal_static_dcore_database_models_proto_EventStore_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.EventStoreProto.internal_static_dcore_database_models_proto_EventStore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.EventStore.class, proto.EventStore.Builder.class);
    }

    // Construct using proto.EventStore.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      eventStoreId_ = "";

      eventName_ = "";

      itemNumber_ = "";

      itemType_ = "";

      userId_ = 0;

      userLogin_ = "";

      nodeId_ = 0;

      nodeCode_ = "";

      if (createdAtBuilder_ == null) {
        createdAt_ = null;
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.EventStoreProto.internal_static_dcore_database_models_proto_EventStore_descriptor;
    }

    @java.lang.Override
    public proto.EventStore getDefaultInstanceForType() {
      return proto.EventStore.getDefaultInstance();
    }

    @java.lang.Override
    public proto.EventStore build() {
      proto.EventStore result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.EventStore buildPartial() {
      proto.EventStore result = new proto.EventStore(this);
      result.eventStoreId_ = eventStoreId_;
      result.eventName_ = eventName_;
      result.itemNumber_ = itemNumber_;
      result.itemType_ = itemType_;
      result.userId_ = userId_;
      result.userLogin_ = userLogin_;
      result.nodeId_ = nodeId_;
      result.nodeCode_ = nodeCode_;
      if (createdAtBuilder_ == null) {
        result.createdAt_ = createdAt_;
      } else {
        result.createdAt_ = createdAtBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.EventStore) {
        return mergeFrom((proto.EventStore)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.EventStore other) {
      if (other == proto.EventStore.getDefaultInstance()) return this;
      if (!other.getEventStoreId().isEmpty()) {
        eventStoreId_ = other.eventStoreId_;
        onChanged();
      }
      if (!other.getEventName().isEmpty()) {
        eventName_ = other.eventName_;
        onChanged();
      }
      if (!other.getItemNumber().isEmpty()) {
        itemNumber_ = other.itemNumber_;
        onChanged();
      }
      if (!other.getItemType().isEmpty()) {
        itemType_ = other.itemType_;
        onChanged();
      }
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (!other.getUserLogin().isEmpty()) {
        userLogin_ = other.userLogin_;
        onChanged();
      }
      if (other.getNodeId() != 0) {
        setNodeId(other.getNodeId());
      }
      if (!other.getNodeCode().isEmpty()) {
        nodeCode_ = other.nodeCode_;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.EventStore parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.EventStore) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object eventStoreId_ = "";
    /**
     * <code>string event_store_id = 1;</code>
     * @return The eventStoreId.
     */
    public java.lang.String getEventStoreId() {
      java.lang.Object ref = eventStoreId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventStoreId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_store_id = 1;</code>
     * @return The bytes for eventStoreId.
     */
    public com.google.protobuf.ByteString
        getEventStoreIdBytes() {
      java.lang.Object ref = eventStoreId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventStoreId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_store_id = 1;</code>
     * @param value The eventStoreId to set.
     * @return This builder for chaining.
     */
    public Builder setEventStoreId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventStoreId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string event_store_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventStoreId() {
      
      eventStoreId_ = getDefaultInstance().getEventStoreId();
      onChanged();
      return this;
    }
    /**
     * <code>string event_store_id = 1;</code>
     * @param value The bytes for eventStoreId to set.
     * @return This builder for chaining.
     */
    public Builder setEventStoreIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventStoreId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eventName_ = "";
    /**
     * <code>string event_name = 2;</code>
     * @return The eventName.
     */
    public java.lang.String getEventName() {
      java.lang.Object ref = eventName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_name = 2;</code>
     * @return The bytes for eventName.
     */
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      java.lang.Object ref = eventName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_name = 2;</code>
     * @param value The eventName to set.
     * @return This builder for chaining.
     */
    public Builder setEventName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string event_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventName() {
      
      eventName_ = getDefaultInstance().getEventName();
      onChanged();
      return this;
    }
    /**
     * <code>string event_name = 2;</code>
     * @param value The bytes for eventName to set.
     * @return This builder for chaining.
     */
    public Builder setEventNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object itemNumber_ = "";
    /**
     * <code>string item_number = 3;</code>
     * @return The itemNumber.
     */
    public java.lang.String getItemNumber() {
      java.lang.Object ref = itemNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string item_number = 3;</code>
     * @return The bytes for itemNumber.
     */
    public com.google.protobuf.ByteString
        getItemNumberBytes() {
      java.lang.Object ref = itemNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string item_number = 3;</code>
     * @param value The itemNumber to set.
     * @return This builder for chaining.
     */
    public Builder setItemNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      itemNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string item_number = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemNumber() {
      
      itemNumber_ = getDefaultInstance().getItemNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string item_number = 3;</code>
     * @param value The bytes for itemNumber to set.
     * @return This builder for chaining.
     */
    public Builder setItemNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      itemNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object itemType_ = "";
    /**
     * <code>string item_type = 4;</code>
     * @return The itemType.
     */
    public java.lang.String getItemType() {
      java.lang.Object ref = itemType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string item_type = 4;</code>
     * @return The bytes for itemType.
     */
    public com.google.protobuf.ByteString
        getItemTypeBytes() {
      java.lang.Object ref = itemType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string item_type = 4;</code>
     * @param value The itemType to set.
     * @return This builder for chaining.
     */
    public Builder setItemType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      itemType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string item_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemType() {
      
      itemType_ = getDefaultInstance().getItemType();
      onChanged();
      return this;
    }
    /**
     * <code>string item_type = 4;</code>
     * @param value The bytes for itemType to set.
     * @return This builder for chaining.
     */
    public Builder setItemTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      itemType_ = value;
      onChanged();
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 user_id = 5;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 user_id = 5;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 user_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object userLogin_ = "";
    /**
     * <code>string user_login = 6;</code>
     * @return The userLogin.
     */
    public java.lang.String getUserLogin() {
      java.lang.Object ref = userLogin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userLogin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_login = 6;</code>
     * @return The bytes for userLogin.
     */
    public com.google.protobuf.ByteString
        getUserLoginBytes() {
      java.lang.Object ref = userLogin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLogin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_login = 6;</code>
     * @param value The userLogin to set.
     * @return This builder for chaining.
     */
    public Builder setUserLogin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userLogin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_login = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserLogin() {
      
      userLogin_ = getDefaultInstance().getUserLogin();
      onChanged();
      return this;
    }
    /**
     * <code>string user_login = 6;</code>
     * @param value The bytes for userLogin to set.
     * @return This builder for chaining.
     */
    public Builder setUserLoginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userLogin_ = value;
      onChanged();
      return this;
    }

    private int nodeId_ ;
    /**
     * <code>int32 node_id = 7;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public int getNodeId() {
      return nodeId_;
    }
    /**
     * <code>int32 node_id = 7;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(int value) {
      
      nodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 node_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      
      nodeId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object nodeCode_ = "";
    /**
     * <code>string node_code = 8;</code>
     * @return The nodeCode.
     */
    public java.lang.String getNodeCode() {
      java.lang.Object ref = nodeCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string node_code = 8;</code>
     * @return The bytes for nodeCode.
     */
    public com.google.protobuf.ByteString
        getNodeCodeBytes() {
      java.lang.Object ref = nodeCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string node_code = 8;</code>
     * @param value The nodeCode to set.
     * @return This builder for chaining.
     */
    public Builder setNodeCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string node_code = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeCode() {
      
      nodeCode_ = getDefaultInstance().getNodeCode();
      onChanged();
      return this;
    }
    /**
     * <code>string node_code = 8;</code>
     * @param value The bytes for nodeCode to set.
     * @return This builder for chaining.
     */
    public Builder setNodeCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeCode_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return createdAtBuilder_ != null || createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
        onChanged();
      } else {
        createdAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
        onChanged();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (createdAt_ != null) {
          createdAt_ =
            com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
        } else {
          createdAt_ = value;
        }
        onChanged();
      } else {
        createdAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    public Builder clearCreatedAt() {
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
        onChanged();
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dcore_database.models.proto.EventStore)
  }

  // @@protoc_insertion_point(class_scope:dcore_database.models.proto.EventStore)
  private static final proto.EventStore DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.EventStore();
  }

  public static proto.EventStore getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventStore>
      PARSER = new com.google.protobuf.AbstractParser<EventStore>() {
    @java.lang.Override
    public EventStore parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EventStore(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EventStore> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventStore> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.EventStore getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

